### ISSUE TITLE
Building with CLI tool doesn't work.

### ISSUE THREAD

**Issue by PrivateCaller** [arl/go-detour#36]
Trying to build a navmesh from an .OBJ file with `./recast build file.bin --input file.obj` runs for a little bit and then fails, with this output:

`panic: untested

goroutine 1 [running]:
github.com/arl/go-detour/recast.delaunayHull(0xc00016a000, 0x1c, 0xc00018e498, 0x300, 0x300, 0x13, 0xc00018e034, 0x7f, 0x7f, 0xc00018f0d8, ...)
	/home/user/go/src/github.com/arl/go-detour/recast/meshdetail.go:704 +0x826
github.com/arl/go-detour/recast.buildPolyDetail(0xc00016a000, 0xc000270000, 0x12, 0x12, 0x3fc0000000000006, 0x23dcccccd, 0xc00018f400, 0xc00018f138, 0xc00018e498, 0x300, ...)
	/home/user/go/src/github.com/arl/go-detour/recast/meshdetail.go:1030 +0x1a2a
github.com/arl/go-detour/recast.BuildPolyMeshDetail(0xc00016a000, 0xc000764000, 0xc00018f400, 0x3dcccccd3fc00000, 0x0, 0xc0032f6000)
	/home/user/go/src/github.com/arl/go-detour/recast/meshdetail.go:447 +0xbbb
github.com/arl/go-detour/sample/solomesh.(*SoloMesh).Build(0xc00018f848, 0x6dc380, 0xc0000100a8)
	/home/user/go/src/github.com/arl/go-detour/sample/solomesh/builder.go:281 +0xb90
github.com/arl/go-detour/cmd/recast/cmd.doBuild(0x81f220, 0xc00007ad50, 0x1, 0x3)
	/home/user/go/src/github.com/arl/go-detour/cmd/recast/cmd/build.go:72 +0xc65
github.com/spf13/cobra.(*Command).execute(0x81f220, 0xc00007acf0, 0x3, 0x3, 0x81f220, 0xc00007acf0)
	/home/user/go/src/github.com/spf13/cobra/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x81efa0, 0x4456ca, 0x808c00, 0xc000000180)
	/home/user/go/src/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/src/github.com/spf13/cobra/command.go:902
github.com/arl/go-detour/cmd/recast/cmd.Execute()
	/home/user/go/src/github.com/arl/go-detour/cmd/recast/cmd/root.go:26 +0x31
main.main()
	/home/user/go/src/github.com/arl/go-detour/cmd/recast/main.go:6 +0x25
`

**Comment by arl** [comment]
Your navmesh might contain some specificities that makes go-detour runs some non-tested functions. 
https://github.com/arl/go-detour/blob/dd2fc8f32e358c730a9f5a782712a2a3e0115b10/recast/meshdetail.go#L704
